# Install script for directory: /home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/libmetal/src/lib

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/build-openamp")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "TRUE")
endif()

# Set default install directory permissions.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/tools/Xilinx/Vitis/2023.2/gnu/armr5/lin/gcc-arm-none-eabi/bin/armr5-none-eabi-objdump")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/alloc.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/alloc.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/alloc.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/assert.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/assert.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/assert.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/atomic.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/atomic.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/atomic.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/cache.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/cache.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/cache.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/compiler.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/compiler.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/compiler.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/condition.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/condition.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/condition.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/config.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/config.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/config.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/cpu.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/cpu.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/cpu.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/device.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/device.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/device.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/errno.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/errno.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/errno.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/dma.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/dma.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/dma.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/io.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/io.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/io.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/irq.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/irq.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/irq.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/irq_controller.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/irq_controller.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/irq_controller.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/list.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/list.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/list.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/log.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/log.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/log.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/mutex.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/mutex.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/mutex.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/shmem.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/shmem.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/shmem.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/sleep.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/sleep.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/sleep.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/softirq.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/softirq.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/softirq.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/spinlock.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/spinlock.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/spinlock.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/sys.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/sys.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/sys.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/time.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/time.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/time.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/utilities.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/utilities.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/utilities.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/version.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/version.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/version.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/compiler/armcc/errno.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/compiler/armcc/errno.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/compiler/armcc/errno.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/compiler/gcc/atomic.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/compiler/gcc/atomic.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/compiler/gcc/atomic.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/compiler/gcc/compiler.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/compiler/gcc/compiler.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/compiler/gcc/compiler.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/compiler/iar/compiler.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/compiler/iar/compiler.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/compiler/iar/compiler.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/compiler/iar/errno.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/compiler/iar/errno.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/compiler/iar/errno.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/processor/arm/atomic.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/processor/arm/atomic.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/processor/arm/atomic.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/processor/arm/cpu.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/processor/arm/cpu.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/processor/arm/cpu.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/system/freertos/alloc.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/system/freertos/alloc.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/system/freertos/alloc.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/system/freertos/assert.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/system/freertos/assert.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/system/freertos/assert.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/system/freertos/cache.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/system/freertos/cache.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/system/freertos/cache.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/system/freertos/condition.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/system/freertos/condition.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/system/freertos/condition.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/system/freertos/io.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/system/freertos/io.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/system/freertos/io.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/system/freertos/irq.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/system/freertos/irq.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/system/freertos/irq.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/system/freertos/log.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/system/freertos/log.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/system/freertos/log.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/system/freertos/mutex.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/system/freertos/mutex.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/system/freertos/mutex.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/system/freertos/sleep.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/system/freertos/sleep.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/system/freertos/sleep.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/system/freertos/sys.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/system/freertos/sys.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/system/freertos/sys.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/system/freertos/device.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/system/freertos/device.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/system/freertos/device.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/system/freertos/zynqmp_r5/sys.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/system/freertos/zynqmp_r5/sys.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/system/freertos/zynqmp_r5/sys.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/metal/system/freertos/xlnx_common/sys.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include" TYPE FILE MESSAGE_LAZY RENAME "metal/system/freertos/xlnx_common/sys.h" FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/include/metal/system/freertos/xlnx_common/sys.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/lib/libmetal.a")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/lib" TYPE STATIC_LIBRARY MESSAGE_LAZY FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/libmetal.a")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/lib/libmetal.a")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/lib" TYPE STATIC_LIBRARY MESSAGE_LAZY FILES "/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/libmetal.a")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/compiler/cmake_install.cmake")
  include("/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/processor/cmake_install.cmake")
  include("/home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/build_configs/gen_bsp/libsrc/libmetal/src/lib/system/cmake_install.cmake")

endif()

