domain_path: /home/prasanna/Apps/Xilinx/vitis_git_setup/kria/push/fw_zynqmp_git/grl_v_epr_pf/zynqmp_fsbl/zynqmp_fsbl_bsp
app_src_dir: /tools/Xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/zynqmp_fsbl
template: zynqmp_fsbl
